# openssl rand -hex 100 | head -c 64
hmacSecret: a4013abf31a6dabd154c95fb93e4c2f4b2f8338107bf0ad1c20eba396f685661
oauth2:
  clientType: confidential # or public
  clientID: test-client-id
  clientSecret: test-client-secret
  redirectURL:
    - http://localhost:8081/oauth2/callback
    - http://localhost:8082/oauth2/callback

database:
  type: postgres
  dataSource: host=127.0.0.1 port=5432 user=user password=password dbname=postgres sslmode=disable
  isDebug: true

github:
  clientID: <gh-client-id>
  clientSecret: <gh-client-secret>
  redirectURL: http://localhost:8080/oauth2/github/callback
  availableOrgTeams:
    - user@example.com
    - <org_name>:<team_name>

session:
  redis:
    address: localhost
    port: 6379
    secret: secret
    serializer: json
