// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/ophum/github-teams-oauth2/ent/accesstoken"
	"github.com/ophum/github-teams-oauth2/ent/code"
	"github.com/ophum/github-teams-oauth2/ent/group"
	"github.com/ophum/github-teams-oauth2/ent/schema"
	"github.com/ophum/github-teams-oauth2/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accesstokenFields := schema.AccessToken{}.Fields()
	_ = accesstokenFields
	// accesstokenDescID is the schema descriptor for id field.
	accesstokenDescID := accesstokenFields[0].Descriptor()
	// accesstoken.DefaultID holds the default value on creation for the id field.
	accesstoken.DefaultID = accesstokenDescID.Default.(func() uuid.UUID)
	codeFields := schema.Code{}.Fields()
	_ = codeFields
	// codeDescClientID is the schema descriptor for client_id field.
	codeDescClientID := codeFields[2].Descriptor()
	// code.DefaultClientID holds the default value on creation for the client_id field.
	code.DefaultClientID = codeDescClientID.Default.(string)
	// codeDescScope is the schema descriptor for scope field.
	codeDescScope := codeFields[3].Descriptor()
	// code.DefaultScope holds the default value on creation for the scope field.
	code.DefaultScope = codeDescScope.Default.(string)
	// codeDescRedirectURI is the schema descriptor for redirect_uri field.
	codeDescRedirectURI := codeFields[4].Descriptor()
	// code.DefaultRedirectURI holds the default value on creation for the redirect_uri field.
	code.DefaultRedirectURI = codeDescRedirectURI.Default.(string)
	// codeDescID is the schema descriptor for id field.
	codeDescID := codeFields[0].Descriptor()
	// code.DefaultID holds the default value on creation for the id field.
	code.DefaultID = codeDescID.Default.(func() uuid.UUID)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescID is the schema descriptor for id field.
	groupDescID := groupFields[0].Descriptor()
	// group.DefaultID holds the default value on creation for the id field.
	group.DefaultID = groupDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
