// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccessToken is the predicate function for accesstoken builders.
type AccessToken func(*sql.Selector)

// Code is the predicate function for code builders.
type Code func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
